version: '3'
services:
  db:
    container_name: postgres
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data

  app:
    container_name: docker-rails
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - '3000:3000'
    depends_on:
      - db

